# Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

Scoring: Out of 18 points in total.  15 points in the report.  3 points in the video summary of your report for a non-technical audience.

For the report:
- Each Developing  => -0.5 pts
- Each Unsatisfactory/Missing => -1 pts
  - until the score is 0

For the video:
- Developing  => -1.5 pts
- Unsatisfactory/Missing => -3 pts

|                                                                                    | Unsatisfactory                                                                                                                                                                                                                                                                                      | Developing                                                                                                                                                                                                                                                                                                                          | Proficient                                                                                                                                                                                                                                                    | Exellent                                                                                                                                                                                                                                                                                                                                                          |
| ---------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Title & abstract                                                                   | Title or abstract is confusing or fails to offer important details about the question, variables, context, or methods of the project.                                                                                                                                                               | Title or abstract lacks relevance or fails to offer appropriate details about the question, variables, context, or methods of the project.                                                                                                                                                                                          | Title and abstract are relevant, offering sufficient details about the research project.                                                                                                                                                                      | Title and abstract are informative, succinct, and clear. It offers specific details about the question, variables, context, and proposed methods of the study.                                                                                                                                                                                                    |
| Background                                                                         | Did not have at least 3 reliable and relevant sources. Or relevant sources were not used in relevant ways                                                                                                                                                                                           | A key component was not connected to the research literature. Selected literature was from unreliable sources. Literary supports were vague or ambiguous.                                                                                                                                                                           | Key research components were connected to relevant, reliable literature.                                                                                                                                                                                      | Narrative integrates critical and logical details from the peer-reviewed or other professional research literature. Each key research component is grounded to the literature. Attention is given to different perspectives, threats to validity, and opinion vs. evidence.                                                                                       |
| Research question & hypothesis                                                     | Research issue remains unclear. The research purpose, questions, hypotheses, definitions or variables and controls are still largely undefined, or when they are are poorly formed, ambiguous, or not logically connected to the description of the problem. Unclear connections to the literature. | Research issue is identified, but statement is too broad or fails to establish the importance of the problem. The research purpose, questions, hypotheses, definitions or variables and controls are poorly formed, ambiguous, or not logically connected to the description of the problem. Unclear connections to the literature. | Identifies a relevant research issue. Research questions are succinctly stated, connected to the research issue, and supported by the literature. Variables and controls have been identified and described. Connections are established with the literature. | Presents a significant research problem related to the chemical sciences. Articulates clear, reasonable research questions given the purpose, design, and methods of the project. All variables and controls have been appropriately defined. Proposals are clearly supported from the research and theoretical literature. All elements are mutually supportive. |
| Data description                                                                   | Did not have references to relevant data sources for this problem. Did not describe the data obtained at those sources                                                                                                                                                                              | A key data source was not referenced or described in satisfactory level of detail                                                                                                                                                                                                                                                   | All relevant data sources were referenced and described in terms of their key variables and size                                                                                                                                                              | Multiple data sources for each aspect of the project, All data sources are fully described and referenced. The details of the descriptions also make it clear how they support the needs ot the project.                                                                                                                                                          |
| Data wrangling                                                                     | Data obviously not tidy and not clean. Or even if they are clean/tidy, there was no demonstration of that fact                                                                                                                                                                                      | Data has some minor problems with tidiness or cleanliness. Potentially these are not problems but it wasn't fully demonstrated to be the case in the code                                                                                                                                                                           | Data are made tidy and clean, or are clearly demonstrated to be so from download                                                                                                                                                                              | Data wrangling is complete, but also particularly thoroughly done for a very tough case. Often free text parsing is a bear like this, and doing it well can mean a million edge cases.                                                                                                                                                                            |
| Data visualizations                                                                | Many plots don't capture useful information, or their display of information is difficult to understand.. Legends, labels, axes, titles, captions, etc of many plots may be poor or missing. Figures are not referenced in the main text.                                                           | Most plots make sense and capture useful information. Legends, labels, axes, titles, captions, etc are mostly legible and adequately describe the content of the figure. Most figures are referenced or explained inside the main text and not just left hanging.                                                                   | Plots make sense and capture useful information. Legends, labels, axes, titles, captions, etc are clearly legible and adequately describe the content of the figure. Figures are referenced or explained inside the main text and not just left hanging.      | Plots are beautiful and information dense. Legends, labels, axes, titles, captions, etc clearly describe the content of the figure. Figures are well integrated with the text.                                                                                                                                                                                    |
| Data analysis and results                                                          | Lacks any metrics or at least metrics that are relevant to the problem                                                                                                                                                                                                                              | Some metrics selected are not appropriate for the problem or the metrics selected are not described sufficiently                                                                                                                                                                                                                    | All metrics described are appropriate and and described sufficiently                                                                                                                                                                                          | The metrics are described clearly and succinctly. Their appropriateness for addressing the research problem is clearly described.                                                                                                                                                                                                                                 |
| Ethics                                                                             | Only tries a baseline model, never advances to proper model/hyper-parameter selection                                                                                                                                                                                                               | Only investigates one minimal aspect of their problem, e.g. just did a single hyperparameter selection on a single model                                                                                                                                                                                                            | Does a good model/hyper-parameter selection. Only attempts minimal secondary analysis                                                                                                                                                                         | Does a good model/hyper-parameter selection. Performs multiple secondary analysis such as learning curves, heat maps looking at where in the parameter space things are good/bad, uses statistical testing                                                                                                                                                        |
| Conclusion and discussion                                                          | Doesn't have a narrative/conclusions of what the report accomplished. Or very minimal conclusions, like "X was best" without anything else                                                                                                                                                          | Has narrative/conclusions, but it feels perfunctory and lacks context. Especially if the limitations and ethics sections are largely junk or missing                                                                                                                                                                                | Properly recapitulates the results and provides context for them. Has a sense of the limitatins and ethical issues.                                                                                                                                           | Clearly recapitulates the results and provides context, including the literature/background Has a sense of what to do next, and has good explorations of the limitations and ethics.                                                                                                                                                                              |
| Documentation and written communication                                            | Code documentation is non-existent or perfunctory. Writing has usage errors, poor fluency, and poor rhetoric. If doc/writing are both like this you get unsatisfacory. If one is unsatisfactory and the other is developing you still get unsatisfactory overall.                                   | Code documentation is only partially there. Writing has some usage errors, some poor fluency, or some poor rhetoric. If doc/writing are both like this you get developing. If one is developing and the other is satisfactory you still get developing.                                                                             | Code is documented throughout. Writing has good fluency, good rhetoric, and at most a few minor errors.                                                                                                                                                       | Code documentation is highly informative with docstrings. Writing is high quality. If both doc/writing are like this you get excellent. If one is satisfactory and the other excellent you still get satisfactory.                                                                                                                                                |
| Video (developing -1.5 points, unsatisfactory -3 points)                           | Video well outside the 3-5min time range. Does not communicate major results at a non-technical level. Has major technical issues such as no sound or not available at link. Unsatisfactory if 2/3 of these are true                                                                                | Video just outside the 3-5min time range. Does not communicate well on some points (either wrong tech level or just confusing). Has technical issues such as poor speech quality on video. Developing if 2/3 of these are true                                                                                                      | Video has good quality and is in within 3-5 min range. Communicates the major results at an accessible level for non-technical people.                                                                                                                        | Video has high production quality and is in within 3-5 min range. Communicates the major results clearly and gives a sense of the methods at an accessible level for non-technical people. Has a wow factor (e.g. funny or original approach)                                                                                                                     |
| Quality modifier (can result in extra credit beyond 18 points for this assignment) | Almost everything was just barely proficient. Lots of minimal effort work. Do not double punish; if they already lost points on the rubric do not invoke this: -0.5 points                                                                                                                        |                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                       More than 5 excellents on this rubric: +0.5 points                                                                                   |

# COGS 108 - Final Project (change this to your project's title)

## Permissions

Place an `X` in the appropriate bracket below to specify if you would like your group's project to be made available to the public, including the names of the authors.

* [  ] YES - make available
* [  ] NO - keep private

## Link to video
https://link.to.your.publicly.viewable.video

## Abstract

Please write one to four paragraphs that describe a very brief overview of why you did this, how you did, and the major findings and conclusions.

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

## Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Hypothesis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Overview of Datasets

## Dataset #1: Yearly Video Game Sales By Genre
Link to dataset: https://public.tableau.com/app/profile/yue.wang7536/viz/VideoGameSalesKaggle_17350173664110/VideoGameSales 

#### Description 
This dataset, scraped from vgchartz.com, includes ranking, name, platform, release year, genre, publisher, and sales for games exceeding 100,000 copies. The metric used is per million copies sold (one singular video game purchased), categorized by regions: NA_Sales, EU_Sales, JP_Sales, Other_Sales, and Global_Sales (the sum of all regions). Our analysis specifically utilizes:

- Sales by Year and Genre (1980-2020): Tracking trends via a stacked area chart
- EU Region (2000-2015): Specifically examining data represented as Zone Sales

#### Concerns regarding Dataset 
- **Population Bias**: Each region contains different population numbers (e.g., North America vs. Japan). Larger populations create larger potential consumer markets, meaning sales can weigh more on market size than actual popularity.
Regulatory Variance: Regional regulations (ratings, advertising, and privacy) influence consumption. Stricter laws or total bans in certain countries effectively control the release and sale of video games.
- **Selection Bias**: Only games with over 100,000 copies sold are included. This favors larger companies and franchises, leading to an underrepresentation of indie and less popular games.

In [1]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION 
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

vg_sales = pd.read_csv('data/00-raw/Sales_by_Year_& _Genre.csv')
vg_sales.head()

   Year Genre  Zone Sales
0  1980   NaN        0.67
1  1981   NaN        1.96
2  1982   NaN        1.65
3  1983   NaN        0.80
4  1984   NaN        2.10

In [2]:
vg_sales.shape

(507, 3)

In [3]:
rows_missing_values = vg_sales[vg_sales.isnull().any(axis=1)]
rows_missing_values.shape

(118, 3)

In [4]:
rows_missing_values

     Year      Genre  Zone Sales
0    1980        NaN        0.67
1    1981        NaN        1.96
2    1982        NaN        1.65
3    1983        NaN        0.80
4    1984        NaN        2.10
..    ...        ...         ...
438  1989  Adventure         NaN
439  1990  Adventure         NaN
466  2017  Adventure         NaN
467  2020  Adventure         NaN
506  2020     Action         NaN

[118 rows x 3 columns]

In [5]:
clean_vg_sales = vg_sales.dropna()
clean_vg_sales[clean_vg_sales.isnull().any(axis=1)]

Empty DataFrame
Columns: [Year, Genre, Zone Sales]
Index: []

In [6]:
clean_vg_sales = clean_vg_sales.sort_values(by=['Zone Sales', 'Year'], ascending=[False, False])
clean_vg_sales = clean_vg_sales.reset_index(drop=True)
print(clean_vg_sales.head(10))

   Year    Genre  Zone Sales
0  2013   Action       45.21
1  2012   Action       42.78
2  2009   Sports       42.17
3  2011   Action       41.04
4  2014   Action       40.48
5  2006   Sports       40.20
6  2008   Action       39.49
7  2009   Action       39.20
8  2010   Action       35.75
9  2011  Shooter       35.31

In [7]:
clean_vg_sales.shape

(389, 3)

In [8]:
clean_vg_sales.head()

   Year   Genre  Zone Sales
0  2013  Action       45.21
1  2012  Action       42.78
2  2009  Sports       42.17
3  2011  Action       41.04
4  2014  Action       40.48

### Dataset #2 (if you have more than one, use name instead of number here)

In [ ]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Results

### Exploratory Data Analysis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your EDA feedback

**NOTE** The final report should not be overly long.  If this EDA step is huge and complicated  and you went down a lot of dead ends, then you should do something about that.  Some options... 

1) remove any EDA you later decided was unecessary side quest.
2) if the code to EDA is very long (in either lines or in time to compute) make sure you write out images of the EDA into `results/` and reload them as images here instead of recalculating it. And make a statement here like "To see the code responsible for EDA analyses see `02-EDACheckpoint.ipynb`."

### First Analysis You Did - Give it a better title

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.  Every project will be different here... but some examples of analyses are: inferential statistics where you calculate p-values (like a t-test or a Monte Carlo simulation), regression models, or a machine learning model

**NOTE** The final report should not be overly long.  If this analysis step is huge and complicated  and you went down a lot of dead ends, then you should do something about that.  Some options... 

1) remove any analysis you later decided was unecessary side quest before checking in for the final hand in
2) if the code to do an analysis is very long (in either lines or in time to compute) put it in a different file.  In that file make write out results of analysis into `results/` and reload the results here instead of recalculating it. And make a statement here like "To see the code responsible for analyses see `path/to/some-file-name.ipynb_or.py`."

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

### Second Analysis You Did - Give it a better title

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.  Every project will be different here... but some examples of analyses are: inferential statistics where you calculate p-values (like a t-test or a Monte Carlo simulation), regression models, or a machine learning model

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

### ETC AD NASEUM

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Discusison and Conclusion

Wrap it all up here.  Somewhere between 3 and 10 paragraphs roughly. 
1. Summarize the important results you made
2. This is a good time to refer back to your Background section and review how this work extended the previous stuff.
3. Try to bring all the different results together into a bigger picture... what have we learned?
4. Often what we learned is confusing.  Discuss if there are contradictory results how that might have happened
5. Discuss the limitations of your work. e.g, is the dataset a biased sample? would more data make you more confident? would longitudinal instead of cross-sectional data helpful? is there evidence that the phenomena you're investigating may change over time? etc
6. If you would like, you can also say what the next steps in this investigation might be if the work was to continue outside this class